name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CACHE_VERSION: 1

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MIX_ENV: "test"
      ELIXIR_VERSION: ${{ matrix.elixir }}
      OTP_VERSION: ${{ matrix.otp }}
    strategy:
      fail-fast: false
      matrix:
        pair:
          - erlang: "23.0"
            elixir: 1.10.4
          - erlang: 22.3
            elixir: 1.10.4
          - erlang: 21.3
            elixir: 1.10.4
          - erlang: 22.3
            elixir: 1.9.4
          - erlang: 21.3
            elixir: 1.9.4
          - erlang: 20.3
            elixir: 1.9.4
          - erlang: 22.3
            elixir: 1.8.1
          - erlang: 21.3
            elixir: 1.8.1
          - erlang: 20.3
            elixir: 1.8.1
          - erlang: 22.3
            elixir: 1.7.3
          - erlang: 21.3
            elixir: 1.7.3
          - erlang: 20.3
            elixir: 1.7.3
          - erlang: 19.3
            elixir: 1.7.3
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.pair.erlang}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Install Dependencies
        run: mix deps.get --only test
      - name: Run Tests
        run: mix test
